DIRTARGET=lark.o
# order here is very important. Must have kbase first
DIROBJS=kbase.o kthread.o main.o page.o sema.o switch.o string.o \
video.o tbase.o traps.o pcibios.o

include $(TOPLEVEL)/Rules.mak

clean:
	rm -rf *.o
